# Generated by Django 2.2 on 2020-05-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20200518_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='platform',
            field=models.CharField(choices=[('SPTY', 'Spotify'), ('SNCD', 'SoundCloud')], max_length=4),
        ),
    ]
