# Generated by Django 2.2 on 2020-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20200518_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Spotify'), (2, 'SoundCloud')]),
        ),
    ]
